---
title: "Project1: Wind power energy part 3"
output: 
  html_document:
  toc: true
  toc_float: true
  # toc_collapsed: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Packages

```{r include=FALSE}
library(dplyr)
library(tidyr)
library(ggplot2)
library(GGally)
library(magrittr)
library(MASS)
```


## Load
```{r}
wind_data <- read.delim("../Data/tuno.txt", header = T, sep = " ")
summary(wind_data)
wind_data$pow.obs.norm <- (wind_data$pow.obs)/5000
wind_data$ws30.norm <- (wind_data$ws30)/max(wind_data$ws30)

wind_data

#normalized_pow.obs <- scale(wind_data$pow.obs)
#colMeans(normalized_pow.obs)
#apply(normalized_pow.obs, 2, sd)
#var(wind_data$pow.obs)
#var(wind_data$ws30)
#var(wind_data$wd30)

```






```{r}
data_transform <- function(y, lambda){
  2 * log(y^lambda/((1-y)^(1-lambda)))
  
}
wind_data$pow.lambda <- data_transform(wind_data$pow.obs.norm, 0.2)
wind_data

model = lm(pow.lambda ~ ws30 + I(ws30^2), data = wind_data)
summary(model)
  

plot(wind_data$ws30, wind_data$pow.lambda)
abline(model)

```

# Fit parameters

```{r}
res = model$residuals

res_matrix <- function(res){
  n = length(res) - 1
  M = matrix(nrow = n, ncol = 2)
  
  for (i in 1:n){
    M[i, 1] = res[i]
    M[i, 2] = res[i+1]
  }
  return(M)
}

nll_multivariate<- function(par, data){
  sigma = par[1]
  par[2] -> p
  Sigma = matrix(data = c(sigma, p*sigma, p*sigma, sigma), nrow = 2, ncol = 2, byrow = T)
  n = length(res_matrix(res))/2
  sum = 0
  
  for (i in 1:n){
      x <- data[i,]
      sum = sum - 1/2*(log(det(Sigma)) + t(x) %*% solve(Sigma) %*% x + 2*log(2*pi))
  
  }
  return(-sum)
}

opt <- nlminb(start = c(1,.5), nll_multivariate, lower = c(1e-16,1e-16), upper = c(1,0.999), data = res_matrix(res))
opt
```

### 
```{r}
hess <- numDeriv::hessian(nll_multivariate, opt$par, data = res_matrix(res))
CI_sigma <- opt$par[1]+c(-1,1)*sqrt(solve(hess[1,1]))*qnorm(0.975)
cat("The wald confidence interval for sigma^2 is ", CI_sigma)
CI_rho = opt$par[2]+c(-1,1)*sqrt(solve(hess[2,2]))*qnorm(0.975)
cat("The wald confidence interval for rho is ", CI_rho)
```


# Compare fisher information

Algebraic fsiher information from a bivariate normal
$$
I\left(\sigma^{2}, \rho\right)=\left(\begin{array}{cc}\frac{n}{\sigma^{4}} & -\frac{n \rho}{\sigma^{2}\left(1-\rho^{2}\right)} \\ -\frac{n \rho}{\sigma^{2}\left(1-\rho^{2}\right)} & \frac{n\left(1+\rho^{2}\right)}{\left(1-\rho^{2}\right)^{2}}\end{array}\right)
$$


```{r}
cat("Numerical matrix values: ", hess)
sigma_MLE <- opt$par[1]
rho_MLE <- opt$par[2]
n <- length(res)

I1 <- n/sigma_MLE^2
I2 <- -n*rho_MLE/(sigma_MLE*(1-rho_MLE^2))
I4 <- n*(1+rho_MLE^2)/(1-rho_MLE^2)^2

cat("\nAlgebraic matrix values: ", matrix(c(I1, I2, I2, I4), nrow = 2, byrow = T))
```


$$
\begin{align}
I_{num}\left(\hat{\sigma^2}, \hat{\rho}\right) &= \begin{bmatrix} 374.9 &&  -111.9 \\ -111.9 && 384.0 \end{bmatrix} \\
I_{alg}\left(\hat{\sigma^2}, \hat{\rho}\right) &= \begin{bmatrix} 376.2 && -112.3 \\ -112.3 && 385.3 \end{bmatrix}
\end{align}
$$
Wow, numerical methods results in nearly the same as the algebraic.
# Contour Plots
```{r}
sigma = seq(0.72,1.1, by = 0.01)
p = seq(0.15,0.45, by = 0.01)

data = res_matrix(res)
print(length(sigma))
Z = matrix(data = NA, nrow = length(sigma), ncol = length(p))
for (i in 1:length(sigma)){
  print(i)
  for (j in 1:length(p)){
    
    Z[i,j] = nll_multivariate(c(sigma[i], p[j]), data)

  }
  
}
A = -Z -(max(-Z))
confint = c(.99, .975, .95, .9, .8, .5)
C = exp(-1/2*qchisq(confint, df = 1))
contour(x = sigma, y = p, exp(A), level=C, xlab = expression(sigma^2), ylab = expression(rho), main = "Countour Plot of confidence regions", labels = confint)
```






# P values for rho. Wald and Likelihood test
## Likelihood ratio test
```{r}
nll_multivariate2<- function(sigma, p, data){
  Sigma = matrix(data = c(sigma, p*sigma, p*sigma, sigma), nrow = 2, ncol = 2, byrow = T)
  n = length(res_matrix(res))/2
  sum = 0
  
  for (i in 1:n){
      x <- data[i,]
      sum = sum - 1/2*(log(det(Sigma)) + t(x) %*% solve(Sigma) %*% x + 2*log(2*pi))
  
  }
  return(-sum)
}



Profile_rho <- function(rho){
  sigma = nlminb(start = c(1), nll_multivariate2, lower = c(1e-16), upper = c(1), p = rho, data = res_matrix(res))$par
  
  nll_multivariate2(sigma, rho, data = res_matrix(res))


}


opt_rho = nlminb(start = c(0.5), Profile_rho, lower = c(1e-16), upper = c(0.999))

objective = -opt_rho$objective
h0 = -Profile_rho(0)

Q = -2*(h0-objective)
p = pchisq(Q, df = 1, lower.tail = F)
cat("P-value for likelihood ratio test:", p)
se = sqrt(solve(hess[2,2]))

z = (objective-h0)/se
p1 = 1-pnorm(z)

cat("P-values for Wald test:", p1)


```

## Profile likelihood and quadratic aprroximation
```{r}
rho <- seq(0,0.5, by = 0.01)
L = sapply(rho,Profile_rho)
plot(rho, -L-max(-L), 'l', ylab = "Normalised Log Likelihood", xlab = expression(rho))
C = -1/2*qchisq(1-0.05, df = 1)
abline(h = C)
curvature = 1/solve(hess)[2,2]
lines(rho,-1/2*curvature * (rho - opt_rho$par)^2, 'l', lty = 2)
```




### Z transform stuff profile likelihood ... idunno ... 
```{r}
nll_multivariate3<- function(l_sigma, z, data){
  Sigma = matrix(data = c(l_sigma, z*l_sigma, z*l_sigma, l_sigma), nrow = 2, ncol = 2, byrow = T)
  n = length(res_matrix(res))/2
  sum = 0
  
  for (i in 1:n){
      x <- data[i,]
      sum = sum - 1/2*(log(det(Sigma)) + t(x) %*% solve(Sigma) %*% x + 2*log(2*pi))
  
  }
  return(-sum)
}



Profile_z <- function(z){
  sigma = nlminb(start = c(1), nll_multivariate3, lower = c(1e-16), upper = c(1), z = z, data = res_matrix(res))$par
  sigma = log(sigma)
  z = 1/2 * log((1+rho)/(1-rho))
  nll_multivariate2(sigma, z, data = res_matrix(res))
}

rho <- seq(0.01, 0.5, by = 0.01)
z <- 1/2 * log((1+rho)/(1-rho))
L = sapply(z,Profile_z)
plot(z, -L-max(-L), 'l', ylab = "Normalised Log Likelihood", xlab = expression(rho))
```




```{r}

acf(res)

nll_ar1 <-function(par){
  theta <- par[1]
  phi <- par[2]
  sigma <- par[3]
  x1 <- res[1]
  L1 = (2*pi*sigma)^(-1/2) * (1-phi^2)^(1/2) * exp(-(1-phi^2)/(2*sigma) *(x1 - theta/(1-phi))^2  )
  -L1
}

nlminb(start = c(0,.5,1), nll_ar1, lower = c(-Inf, -0.999, 0), upper = c(Inf, 0.999, Inf))
```

